export default {
  ACCOUNT_STATUS: {
    GET: 'GET_ACCOUNT_STATUS',
    OPTION_DATE: 'UPDATE_OPTION_DATE',
    FILTER: 'SET_FILTER',
    SET_LOADING_ACCOUNT: 'SET_LOADING_ACCOUNT',
    TOTAL_SALES: 'SET_TOTAL_SALES',
  }
}